// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq84AnAWvlIVibVxC1yKxQHD5I5x5qYYE',
    appId: '1:926519603344:web:9faa288b451ed7a81b6815',
    messagingSenderId: '926519603344',
    projectId: 'proyectsocialmediaapp',
    authDomain: 'proyectsocialmediaapp.firebaseapp.com',
    storageBucket: 'proyectsocialmediaapp.firebasestorage.app',
    measurementId: 'G-0QLZEX1NCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbs3nU9RRxz-ZkfwT6XR_u9alQhcheczk',
    appId: '1:926519603344:android:a29dbad4e78b2f1a1b6815',
    messagingSenderId: '926519603344',
    projectId: 'proyectsocialmediaapp',
    storageBucket: 'proyectsocialmediaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9MlXJ1gOIYB6OZz7M6rQYrASfe-CfQKE',
    appId: '1:926519603344:ios:ffc10e73f40a99ad1b6815',
    messagingSenderId: '926519603344',
    projectId: 'proyectsocialmediaapp',
    storageBucket: 'proyectsocialmediaapp.firebasestorage.app',
    iosBundleId: 'com.example.proyectofinal',
  );

}